name: tr.Extramentals
version: '${project.version}'
main: me.dragontos.extramentals.Extramentals
api-version: 1.15
commands:
  Extramentals:
    subcommands:
      hello:
      bye:
  Discord:
    subcommands:
      dc:
  Gui:
  gmc:
  gms:
  gma:
  gmsp:
  fly:
  heal:
  feed:
  god:

