name: tr.Extramentals
version: 0.0.2
main: me.dragontos.extramentals.Extramentals
api-version: 1.15
depends: [PlaceholderAPI]
commands:
  Extramentals:
    subcommands:
      hello:
      bye:
  Discord:
  Dc:
  Gui:
  gm:
  gmc:
  gms:
  gma:
  gmsp:
  fly:
  heal:
  feed:
  god:
  day:
  night:
  ec:
  enderchest:

